services:
  - type: web
    name: andrew3d-portfolio
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_SITE_URL
        value: https://andrew3d-portfolio.onrender.com
